### ISSUE TITLE
.gitignore の設定

### ISSUE THREAD

**Issue by Okabe-Junya** [ssf2xguile/flask-tutorial#1]
`__pycache__` みたいな余計なファイルがpushされてるから `.gitignore`  設定した方がよき

---
【参考】
https://github.com/github/gitignore/blob/main/Python.gitignore

**Comment by ssf2xguile** [comment]
あ、マジそうなん？直しておくわ

2022年8月15日(月) 17:21 Junya Okabe ***@***.***>:

**Comment by Okabe-Junya** [comment]
外す時に，

```
% git rm --cached <file_name>
```

もお忘れなく．
